### PR TITLE
Add bytelevel normalizer to fix decode when adding tokens to BPE

### LINKED ISSUE #1392: added_tokens with bytemap charaters in ByteLevel could not be decoded correctly
I just found that if added tokens contain some characters that exist in the byte map for ByteLevel preprocessor could not be decoded correctly.
This is a script to reproduce the problem with version 0.14.1
```python
from tokenizers import Tokenizer
from tokenizers import normalizers
from tokenizers.pre_tokenizers import (
    ByteLevel,
)
from tokenizers.models import BPE
from tokenizers import decoders
tokenizer = Tokenizer(BPE())
tokenizer.normalizer = normalizers.Sequence([])

tokenizer.pre_tokenizer = Sequence(
    [
        ByteLevel(add_prefix_space=False, use_regex=False),
    ])
tokenizer.add_tokens(["ilÖveyou"])
# Ö is the character representing for 0xf6
tokenizer.decoder = decoders.ByteLevel()
encode_result = tokenizer.encode("ilÖveyou")
print(encode_result.ids)
print(tokenizer.decode(encode_result.ids))
```
the output wil be 
```
[0]
il�veyou
```

I believe the problem comes from 
https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/tokenizer/mod.rs#L832-L836
I don't think added token should be sent to bytelevel decoder for it is extacted before pretokenize.

### PR DESCRIPTION
**Pull request by ArthurZucker**
This revert the previous breaking change. 

Also add a new `ByteLevel` normalizer, which replaces the ByteLevel pre_tokenizer.
Checked that we can add chines / Cyrillic tokens which are properly encoded and decoder. 

Fixes #1392

### CODE REVIEW

File: tokenizers/src/tokenizer/mod.rs [hunk 1]
```diff
@@ -847,35 +847,22 @@ where
...
+                self.added_vocabulary
+                    .id_to_token(*id, &self.model)
+                    .filter(|token| {
+                        !skip_special_tokens || !self.added_vocabulary.is_special_token(token)
+                    })
+            })
+            .collect::<Vec<_>>();
+
+        if let Some(decoder) = &self.decoder {
+            decoder.decode(tokens)
```
Comment (ArthurZucker) [inline tokenizers/src/tokenizer/mod.rs:862]: reverted to what we originally had

File: tokenizers/src/pre_tokenizers/byte_level.rs [hunk 2]
```diff
@@ -11,7 +11,7 @@ use crate::utils::macro_rules_attribute;
 
 /// Converts bytes to unicode characters.
 /// See https://github.com/openai/gpt-2/blob/master/src/encoder.py#L9
-fn bytes_char() -> HashMap<u8, char> {
+pub fn bytes_char() -> HashMap<u8, char> {
```
Comment (McPatate) [inline tokenizers/src/pre_tokenizers/byte_level.rs:14]:
```suggestion
pub(crate) fn bytes_char() -> HashMap<u8, char> {
```

File: tokenizers/src/tokenizer/added_vocabulary.rs [hunk 3]
```diff
@@ -216,17 +216,14 @@ impl AddedVocabulary {
     }
 
     /// Get the token matching the given id if it exists
-    #[deprecated(
-        since = "0.19.0",
-        note = "please use `added_vocabulary.simple_id_to_token(id).or_else(|| model.id_to_token(id)` instead"
-    )]
```
Comment (McPatate) [inline tokenizers/src/tokenizer/added_vocabulary.rs:222]: Is this not deprecated anymore?

File: tokenizers/src/tokenizer/added_vocabulary.rs [hunk 4]
```diff
@@ -216,17 +216,14 @@ impl AddedVocabulary {
...
     pub fn id_to_token(&self, id: u32, model: &impl Model) -> Option<String> {
         self.added_tokens_map_r
             .get(&id)
             .map(|t| t.content.clone())
             .or_else(|| model.id_to_token(id))
     }
 
+    //
```
Comment (McPatate) [inline tokenizers/src/tokenizer/added_vocabulary.rs:226]:
```suggestion
```

File: tokenizers/src/tokenizer/pre_tokenizer.rs [hunk 5]
```diff
@@ -51,7 +51,7 @@ impl From<(NormalizedString, Option<Vec<Token>>)> for Split {
 /// original string.
 #[derive(Debug, Clone, PartialEq, Eq)]
 pub struct PreTokenizedString {
-    original: String,
+    pub original: String,
```
Comment (McPatate) [inline tokenizers/src/tokenizer/pre_tokenizer.rs:54]: I'm not seeing `.original` anywhere, why do you need this?

Also if it is for internal usage, `pub(crate)`

File: tokenizers/src/normalizers/byte_level.rs [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+    }
+
+    pub fn alphabet() -> HashSet<char> {
+        BYTES_CHAR.values().copied().collect()
+    }
+}
+
+impl Normalizer for ByteLevel {
+    /// Strip the normalized string inplace
+    fn normalize(&self, normalized: &mut NormalizedString) -> Result<()> {
```
Comment (McPatate) [inline tokenizers/src/normalizers/byte_level.rs:34]: Why doesn't this live in `NormalizedString` like so:
```rs
impl NormalizedString {
  fn normalize_byte_level(&mut self) -> Result<()> { // ... }
}
```
?
Feels a bit weird to have an empty stateless struct for just a function, but may be due to the structure of tokenizers / python.

File: tokenizers/src/models/bpe/trainer.rs [hunk 7]
```diff
@@ -282,8 +282,8 @@ impl BpeTrainer {
         for c in &self.initial_alphabet {
             alphabet
                 .entry(*c)
-                .and_modify(|cnt| *cnt = std::usize::MAX)
-                .or_insert(std::usize::MAX);
+                .and_modify(|cnt| *cnt = usize::MAX)
+                .or_insert(usize::MAX);
```
Comment (McPatate) [inline tokenizers/src/models/bpe/trainer.rs:286]: did rustfmt do that?

File: tokenizers/src/tokenizer/added_vocabulary.rs (hunk 3 above)
Comment (ArthurZucker) [reply tokenizers/src/tokenizer/added_vocabulary.rs:222]: will rebase on main to fix this

File: tokenizers/src/tokenizer/pre_tokenizer.rs (hunk 5 above)
Comment (ArthurZucker) [reply tokenizers/src/tokenizer/pre_tokenizer.rs:54]: good catch, I think I no longer need this!

File: tokenizers/src/models/bpe/trainer.rs (hunk 7 above)
Comment (ArthurZucker) [reply tokenizers/src/models/bpe/trainer.rs:286]: clippy but it breaks stuff
