### PR TITLE
rust: fix `OnlyFirst` and `OnlySecond` truncation strategies

### LINKED ISSUE #108: `OnlyFirst` and `OnlySecond` truncation strategies
The current behavior for `OnlyFirst` and `OnlySecond` truncation strategies is not the one I would expect, and diverges from the current behavior in [transformers](https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils.py#L1107-L1113):

https://github.com/huggingface/tokenizers/blob/88391dd18501ee672bee155a15f16632f2e0ae57/tokenizers/src/utils.rs#L87-L99

It currently takes only the first encoding (`OnlyFirst`) or the second one (`OnlySecond`), and then truncates it to make its length less than the desired `max_length`.

But this doesn't guarantee that the combined encodings have a length inferior to `max_length`, which is the behavior I was expecting: those strategies should take into account the combined encodings length when truncating only the first or second one.

What do you think @n1t0 @mfuntowicz?

### PR DESCRIPTION
**Pull request by Pierrci**
Fixes #108: behavior for `OnlyFirst` and `OnlySecond` truncation strategies aligned with current `transformers` behavior.

They now take into account the length of the combined encoding, potentially raising a new `SequenceShorterThanNumberTokensToRemove` error.

### CODE REVIEW

**Comment by Pierrci** [comment]
My first ever Rust PR @n1t0, so don't hesitate to point any problem! 😁🤞

File: tokenizers/src/utils.rs [hunk 1]
```diff
@@ -93,8 +98,11 @@ pub fn truncate_encodings(
                 Err(Box::new(Error::SecondSequenceNotProvided))
             }?;
 
-            if target.get_ids().len() > params.max_length {
-                target.truncate(params.max_length, params.stride);
+            let target_len = target.get_ids().len();
+            if target_len > to_remove {
+                target.truncate(target_len - to_remove, params.stride);
+            } else {
+                return Err(Box::new(Error::SequenceShorterThanNumberTokensToRemove));
```
Comment (n1t0) [inline tokenizers/src/utils.rs]: What do you think about `SequenceTooShort`? I would also change the message in the `Display` implementation to say something like `Sequence to truncate too short to respect the provided max_length`.

Comment (Pierrci) [reply tokenizers/src/utils.rs]: Oh yeah sure, I really thought this name was too long but couldn't find anything better ^^' 👍

Comment (julien-c) [reply tokenizers/src/utils.rs]: was the name of the option longer than the number of tokens to remove? 😅
